name: build and test

on:
  pull_request:
    branches: [main, release/*]
    paths:
      - ".github/workflows/build-and-test.yml"
      - "__tests__/**"
      - "src/**"
      - "*.config.ts"
      - "*.setup.ts"
      - "*.json"
      - "*.lock"
  push:
    branches: [main, release/*]
    paths:
      - ".github/workflows/build-and-test.yml"
      - "__tests__/**"
      - "src/**"
      - "*.config.ts"
      - "*.setup.ts"
      - "*.json"
      - "*.lock"
  release:
    types: [created, published]

jobs:
  build:
    name: build-and-test-nodejs-${{matrix.node-version}}-on-${{matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Modules
        run: yarn install

      - name: Run Tests
        run: yarn test
